# Generated by Django 2.2.11 on 2020-03-31 12:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200331_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posteo',
            new_name='Publicacion',
        ),
    ]
