# Generated by Django 2.2.11 on 2020-03-31 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200331_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publicacion',
            new_name='Post',
        ),
    ]
